services:
  ocr_oneshot:
    build: .
    container_name: ocr_oneshot
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: "no"
