services:
  ocr_oneshot:
    build: .
    container_name: ocr_oneshot
    network_mode: host
    volumes:
      - /volume1/Main/Main/IncomingPW:/app/IncomingPW
      - /volume1/Main/Main/ProcessedPOs:/app/ProcessedPOs
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_URL=http://localhost:11434
      - OLLAMA_MODEL=gemma2:2b
      - OCR_INCOMING=/app/IncomingPW
      - OCR_PROCESSED=/app/ProcessedPOs
      - LOG_DIR=/app/logs
    restart: "no"
