version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.unified
    volumes:
      - "//bluecloud2/Main/scripts/unified_ocr_pipeline:/workspaces/unified_ocr_pipeline:cached"
    command: sleep infinity
